config/routes.rb
Starter::Application.routes.draw do

  match 'home' => 'pages#home'
  
  match 'about' => 'pages#about'
  
  match 'about_founder' => 'pages#about_founder'
  
  match 'about_cost' => 'pages#about_cost'
  
  match 'contact' => 'pages#contact'
  
  match 'services' => 'pages#services'
  
  match 'services_web' => 'pages#services_web'

  match 'services_consult' => 'pages#services_consult'
  
  match 'services_training' => 'pages#services_training'
  
  match 'services_photo' => 'pages#services_photo'
  
  match 'portfolio' => 'pages#portfolio'
  
  match 'artificialdesigns' => 'webs#artificialdesigns'
  
  match 'alliancepublishingpress' => 'webs#alliancepublishingpress'
 

  get "pages/web_portfolio"

  get "pages/photo_portfolio"

  get "pages/links"

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
#    render :layout => 'home_layout'
  end
  
  def about
  end

  def about_founder
  end

  def about_cost
  end
  
  def services  
  end
  
  def services_web
  end

  def services_consult
  end
  
  def services_training
  end
  
  def services_photo
  end
  
  def artificialdesigns
  end
  
  def consultancy_services
  end

  def photography
  end

  def portfolio
  end

  def photo_portfolio
  end

  def contact
  end

  def links
  end
end

app/controllers/webs_controller.rb
class WebsController < ApplicationController
  def alliancepublishingpress
  end

  def minnawaring
  end

  def elspics
  end

  def bluedrummusic
  end

  def lifestylepix
  end

  def artificialdesigns
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/webs_helper.rb
module WebsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Starter</title>
  
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "blueprint/screen" %>    
  <%= stylesheet_link_tag    "application"%>
  <%= javascript_include_tag "application", :media => "all"%>
  <%#= javascript_include_tag  "jquery.dimensions.min" %>
  <%#= javascript_include_tag "jquery.colorbox-min.js" %>


  <!--[if lt IE 9]><%= stylesheet_link_tag "blueprint/ie" %><![endif]-->

  <!--[if lt IE 9]><%= stylesheet_link_tag "menufix_ie" %><![endif]-->
  <!--[if lte IE 7]><%= stylesheet_link_tag "menufix_ie7" %><![endif]-->
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>
standard page
</body>
</html>

app/views/layouts/application.html.haml
-# coding: UTF-8
!!!
%html.no-js
  %head
    %title the-feel: web design, IT consultancy and photography
    %meta(name="description" content="a description")
    %meta(name="author" content="the-feel : Eric Waring")
    /%meta(name="copyright" content="Copyright the-feel #{Time.now.year}. All rights reserved.")
    
    = stylesheet_link_tag "blueprint/screen"
    = stylesheet_link_tag "floatbox.css"
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = javascript_include_tag "floatbox.js"
    /[if lte IE 7]
      = stylesheet_link_tag "menufix_ie7"
    /[if lt IE 9]
      = stylesheet_link_tag "blueprint/ie"
      = stylesheet_link_tag "menufix_ie"
    /[if lt IE 10]
      /= stylesheet_link_tag "ie_menublur"

    = csrf_meta_tags

  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is a?(String)

    #the_wrapper.container
      .row
        .twocol#sidebar
          = link_to (image_tag 'logos/the-feel-web-logo1.png', :id => 'logo'), home_path, :id => 'logoa'
          %nav.bmenu.blur
            %ul
              %li.transit= link_to 'home', home_path
            %ul.headera
              %li.transit= link_to 'about', about_path
              .allsubmenu
                %li.transit.submenua= link_to 'about the-feel', about_path
                %li.transit.submenua= link_to 'about the-founder', about_founder_path
                %li.transit.submenua= link_to 'about the-cost', about_cost_path
            %ul.headera
              %li.transit= link_to 'services', services_path
              .allsubmenu
                %li.transit.submenu= link_to 'web design', services_web_path
                %li.transit.submenu= link_to 'consultancy', services_consult_path
                %li.transit.submenu= link_to 'training', services_training_path 
                %li.transit.submenu= link_to 'photography', services_photo_path 
            %ul
              %li= link_to 'portfolio', portfolio_path 
            /%ul
            /  %li= link_to 'projects', home_path
            /%ul
            /  %li= link_to 'links', home_path
            %ul
              %li= link_to 'contact', contact_path
        .eightcol#mainContent
          =yield
        .twocol.last
  

app/views/layouts/home_layout.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "home.html.erb" %>
<%= yield %>
home page

app/views/layouts/home_layout.html.haml
-# coding: UTF-8
!!!
%html
  %head
    %title the-feel: web design, IT consultancy and photography
    %meta(name="description" content="a description")
    %meta(name="author" content="the-feel : Eric Waring")
    /%meta(name="copyright" content="Copyright the-feel #{Time.now.year}. All rights reserved.")

    = stylesheet_link_tag "blueprint/screen"
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    /[if lte IE 7]
      = stylesheet_link_tag "menufix_ie7"
    /[if lt IE 9]
      = stylesheet_link_tag "blueprint/ie"
      = stylesheet_link_tag "menufix_ie"
      
    /[if lt IE 10]
      /= stylesheet_link_tag "ie_menublur"
      /%script(src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js")
    = csrf_meta_tags

  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is a?(String)

    #main_wrapper.container
      .row
        .twocol#sidebar
          = image_tag 'logos/the-feel-web-logo1.png'
        .eightcol
          %header
            %h1 the-feel web design, IT consultancy and photography
        .twocol.last
      .row#home_row
        .twocol
        .eightcol
          = yield
        .twocol.last

app/views/layouts/webs.html.haml
=yield

app/views/layouts/xapplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Starter</title>
  
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "blueprint/screen" %>    
  <%= stylesheet_link_tag    "application"%>
  <%= javascript_include_tag "application", :media => "all"%>
  <%#= javascript_include_tag  "jquery.dimensions.min" %>
  <%#= javascript_include_tag "jquery.colorbox-min.js" %>


  <!--[if lt IE 9]><%= stylesheet_link_tag "blueprint/ie" %><![endif]-->

  <!--[if lt IE 9]><%= stylesheet_link_tag "menufix_ie" %><![endif]-->
  <!--[if lte IE 7]><%= stylesheet_link_tag "menufix_ie7" %><![endif]-->
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>
standard page
</body>
</html>

app/views/layouts/xhome_layout.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "home.html.erb" %>
<%= yield %>
home page

app/views/layouts/xxhome_layout.html.haml
-# coding: UTF-8
!!!
%html
  %head
    %title the-feel: web design, IT consultancy and photography
    %meta(name="description" content="a description")
    %meta(name="author" content="the-feel : Eric Waring")
    /%meta(name="copyright" content="Copyright the-feel #{Time.now.year}. All rights reserved.")

    = stylesheet_link_tag "blueprint/screen"
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    /[if lte IE 7]
      = stylesheet_link_tag "menufix_ie7"
    /[if lt IE 9]
      = stylesheet_link_tag "blueprint/ie"
      = stylesheet_link_tag "menufix_ie"
    /[if lt IE 10]
      /= stylesheet_link_tag "ie_menublur"
      /%script(src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js")
    = csrf_meta_tags

  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is a?(String)

    #main_wrapper.container
      .row
        .twocol#sidebar
          = image_tag 'logos/the-feel-web-logo1.png'
        .eightcol
          %header
            %h1 the-feel web design, IT consultancy and photography
        .twocol.last
      .row#home_row
        .twocol
        .eightcol
          = yield
        .twocol.last

app/views/pages/about.html.haml
.row
  .twelvecol.last
    %header
      %h1 About the-feel
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          the-feel is a web design and photography company based in North London and founded by former teacher and IT Manager/Director 
          Eric Waring.<br /><br /> the-feel delivers high quality, bespoke, yet affordable web sites for the discerning client who requires something different
          from common, template driven, off the shelf designs. We particularly enjoy working with small businesses and creatives.
          <br /><br />As well as web design we can offer IT consultancy, trouble shooting, database work, IT solution development (spreadsheets/automated processes)
          and photography. Explore the site and get in touch  - we don't bite and are convinced that we can help improve your business:-)

      .circlePic#mover
        = image_tag 'coloured_balls2.png'

      .abcirc
        .description.blur
          %ul
            <br />
            %li About:
            %li= link_to 'the-feel', about_path
            %li= link_to 'the-founder', about_founder_path
            /%li= link_to 'the-cost', about_cost_path 

app/views/pages/about_cost.html.haml
.row
  .twelvecol.last
    %header
      %h1 About the-feel
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          money money money money!!!!!!!!


      .circlePic#mover
        = image_tag 'coloured_balls.png'

      .abcirc
        .description.blur
          %ul
            %li About:
            %li= link_to 'the-feel', about_path
            %li= link_to 'the-founder', about_founder_path
            %li= link_to 'the-cost', about_cost_path 

app/views/pages/about_founder.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-founder : Eric Waring 
      
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          Eric is an experienced IT professional having spent 15 years teaching IT followed by ten years in industry as IT Director.
          He is also a successful photographer having had work published in books, magazines and on websites. 
          <br /><br />This gives him a unique skill set perfectly 
          suited to web and business solution design: a deep understanding of your business needs, excellent communication skills and creativity.
          He also has a strong team of graphic designers backing him up.
          <br /><br />He has degrees in Physics and Computing and is a member of the 
          = link_to 'BCS', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#hiddenBCS"
          <br /><br /> In his 'spare' time he loves listening to alternative (noise!) music and photographing gigs.

      .circlePic#mover
        = image_tag 'lrg_eric.png'

      .abcirc
        .description.blur
          %ul
            <br />
            %li About:
            %li= link_to 'the-feel', about_path
            %li= link_to 'the-founder', about_founder_path
            /%li= link_to 'the-cost', about_cost_path 

#hiddenBCS
  Eric Waring<br />
  = image_tag 'mbcs-logo-colour-small.jpg'
  #smallText
    Click below to visit the website of the<br /><br />
  = link_to ('BCS, The Chartered Institute for IT'), 'http://www.bcs.org/', :class => 'floatbox'
  <br />&nbsp;
  

app/views/pages/contact.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-feel : photography
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          We pride ourselves on being approachable, friendly people so please contact us to either have a chat or to arrange a 
          time to meet and discuss your requirements over a coffee (or a beer!)<br /><br /><br />

          %ul
            %li 
              email:
              =mail_to 'ericw@the-feel.co.uk', 'ericw@the-feel.co.uk'
              <br /><br />
            %li mobile: 07813 300 602<br /><br />
            .smaller
              %li the-feel ltd
              %li Registered in England and Wales
              %li Company No. 7699718
              %li Registered Address:
              %li 93c Ferme park Road
              %li London, N8 9SA


      .circlePic#mover
        = image_tag 'moreballs.png'

  

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p><%= home_path %></p>

app/views/pages/home.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-feel web design, IT consultancy and photography
.row#home_row
  .twelvecol.last
    .home_wrapper
      .images#images
        = image_tag 'disc1.png', :alt => '1', :id => "image_about", :style => "display:block;"
        = image_tag 'disc2.png', :id => "image_services", :alt => '2'
        = image_tag 'disc3.png', :id => "image_portfolio", :alt => '3'
        = image_tag 'disc4.png', :id => "image_contact", :alt => '4'

      .circleBig
        #menu.menu
          = link_to 'about', about_path, :class => 'about', :id => 'about' 
          = link_to 'services', services_path, :class => 'services', :id => 'services'
          = link_to 'portfolio', portfolio_path, :class => 'portfolio', :id => 'portfolio'
          = link_to 'contact', contact_path, :class => 'contact', :id => 'contact'

      .small_circle#circle_about
        .description.blur
          %ul
            <br />
            %li= link_to 'the-feel', about_path
            %li= link_to 'the-founder', about_founder_path
            /%li= link_to 'the-cost', "#"

      .small_circle#circle_services
        .description.blur
          %ul
            %li= link_to 'web', services_web_path
            %li= link_to 'consultancy', services_consult_path
            %li= link_to 'photography', services_photo_path

      .small_circle#circle_portfolio
        .description.blur
          %ul
            <br />
            %li= link_to 'web sites', portfolio_path
            /%li= link_to 'photography', services_photography_path

      .small_circle#circle_contact
        .description.blur
          %ul
            <br />
            %li= link_to 'the-feel', contact_path
            %li= link_to 'other sites', portfolio_path
            /%li= link_to 'links', "#"

    #home_intro
      the-feel offer high quality, bespoke web design, IT consultancy, data services and photography for small businesses. Your one-stop shop for all your IT needs! 
      <br /><br />
      click on the links in the circles to find out more

app/views/pages/home.html_1.haml
/%h1 Pages#home
/%p Find me somewhere
/%p
/  = home_path 
/  again
.home_wrapper
  .images#images
    = image_tag 'lrg_eric.png', :alt => '1', :id => "image_about", :style => "display:block;"
    = image_tag 'lrg_mat.png', :id => "image_services", :alt => '2'
    = image_tag 'lrg_the-feel-logo.png', :id => "image_portfolio", :alt => '3'
  
  .circleBig
    #menu.menu
      = link_to 'about', '', :class => 'about', :id => 'about' 
      = link_to 'services', '', :class => 'services', :id => 'services'
      = link_to 'portfolio', '', :class => 'portfolio', :id => 'portfolio'
      = link_to 'contact', '', :class => 'contact', :id => 'contact'

  .small_circle#circle_about
    .description
      %ul
        %li= link_to 'the-feel', about_path
        %li= link_to 'the-founder', "#"
        %li= link_to 'the-cost', "#"

  .small_circle#circle_services
    .description
      %ul
        %li= link_to 'web', "#"
        %li= link_to 'consultancy', "#"
        %li= link_to 'photography', "#"

  .small_circle#circle_portfolio
    .description
      %ul
        %li= link_to 'web sites', "#"
        %li= link_to 'photography', "#"

  .small_circle#circle_contact
    .description
      %ul
        %li= link_to 'the-feel', "#"
        %li= link_to 'other sites', "#"
        %li= link_to 'links', "#"

#home_intro
  the-feel offer high quality, bespoke web design, IT consultancy, data services and photography for small businesses. Your one-stop shop for all your IT needs! 
  <br /><br />
  click on the links in the circles to find out more

app/views/pages/links.html.erb
<h1>Pages#links</h1>
<p>Find me in app/views/pages/links.html.erb</p>

app/views/pages/services.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-feel : the-services 
      
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#services
          the-feel are able to offer the following high quality, bespoke services at competitive rates, please click on the links below for further details:<br /><br />
          %ul.articleblur
            %li= link_to 'Web site development and design', services_web_path 
            %li= link_to 'IT consultancy', services_consult_path
            %li= link_to 'Data processing and database work',services_consult_path
            %li= link_to 'IT training and tutoring', services_training_path
            %li= link_to 'Photography', services_photo_path
          <br />we can also offer combinations of the above with substantial discounts - please get in 
          =mail_to 'ericw@the-feel.co.uk', 'touch', :subject => 'the-feel services enquiry'
          to discuss your requirements!

      .circlePic#mover
        = image_tag 'greenbubbles.png'

      .abcirc
        .description.blur
          %ul
            %li Services:
            %li= link_to 'web design', services_web_path
            %li= link_to 'consultancy', services_consult_path
            %li= link_to 'training', services_training_path 
            %li= link_to 'photography', services_photo_path 

#hiddenBCS
  Eric Waring<br />
  = image_tag 'mbcs-logo-colour-small.jpg'
  #smallText
    Click below to visit the website of the<br /><br />
  = link_to ('BCS, The Chartered Institute for IT'), 'http://www.bcs.org/', :class => 'floatbox'
  <br />&nbsp;
  

app/views/pages/services_photo.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-feel : photography
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          On top of the IT work we are pleased to be able to offer a top quality photography service for
          <br /><br />
          %ul
            %li products<br /><br />
            %li interiors<br /><br />
            %li staff<br /><br />
            %li abstract pieces<br /><br />
            %li music and<br /><br />
            %li events.


      .circlePic#mover
        = image_tag 'sheffield2.png'

      .abcirc
        .description.blur
          %ul
            %li Services:
            %li= link_to 'web design', services_web_path
            %li= link_to 'consultancy', services_consult_path
            %li= link_to 'training', services_training_path 
            %li= link_to 'photography', services_photo_path  

app/views/pages/services_training.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-feel : training
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          Eric has trained hundreds of people in the use of Office software from beginner to very advanced. Also as a 
          teacher he has taught IT/computing, Physics and Maths to A-level. Please 
          =mail_to 'ericw@the-feel.co.uk', 'contact', :subject => 'Training/tutoring Enquiry' 
          him for further details on training in <br /><br />
          %ul
            %li Word/Excel/Access
            %li Macros / VB (Visual Basic)
            %li Photoshop / Lightroom
            %li Database development
            %li Network management<br /><br />
          or tutoring at GCSE/A-level in<br /><br />
          %ul
            %li IT / Computing
            %li Physics
            %li Maths
            


      .circlePic#mover
        = image_tag 'dome2.png'

      .abcirc
        .description.blur
          %ul
            %li Services:
            %li= link_to 'web design', services_web_path
            %li= link_to 'consultancy', services_consult_path
            %li= link_to 'training', services_training_path 
            %li= link_to 'photography', services_photo_path  

app/views/pages/services_web.html.haml
.row
  .twelvecol.last
    %header
      %h1 the-feel : web development
.row#home_row
  .twelvecol.last
    .content_wrapper

      .circleBorder
        %article#about-the-feel
          With our extensive business experience we are able to understand your requirements and work closely with you to produce a site which 
          expresses your individuality and 
          =link_to 'USP', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#USP innerBorder:0 fadeDuration:4 mouseSpeed:30 attachToHost:true placement:top"
          whilst maintaining <br />useability for your visitors.<br /><br />
          We use cutting edge web technology to develop bespoke websites using the latest techniques to be found - including some yet to be discovered!<br /><br />
          Technologies we use include 
          =link_to 'HTML5', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#HTMLinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          , 
          =link_to 'CSS3', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#cssinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          , 
          =link_to 'JavaScript', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#jsinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          , 
          =link_to 'jQuery', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#jqinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          , 
          =link_to 'Ajax', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#ajinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          , 
          =link_to 'MySQL', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#mysqlinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          and 
          =link_to 'Ruby on Rails', '#', :class => 'fbTooltip', :'data-fb-tooltip' => "source:#rorinfo innerBorder:0 fadeDuration:4 maxContentWidth:300 mouseSpeed:30 attachToHost:true placement:top"
          , together ensuring compatibility across the board.<br /><br />
          All our sites are SEO optimised and we can also offer web hosting and email with the first year free.<br />
          Get in 
          =mail_to 'ericw@the-feel.co.uk', 'touch', :subject => 'Web Site Enquiry'
          to discuss your needs.

      .circlePic#mover
        = image_tag 'balls.png'

      .abcirc
        .description.blur
          %ul
            %li Services:
            %li= link_to 'web design', services_web_path
            %li= link_to 'consultancy', services_consult_path
            %li= link_to 'training', services_training_path 
            %li= link_to 'photography', services_photo_path 

.hidden_elements
  #USP
    Unique Selling Point
  #HTMLinfo
    =link_to 'HTML5', 'http://www.webopedia.com/TERM/H/HTML5.html', :class => 'floatbox' 
    <br />HTML5 is the latest version of the HyperText Markup Language which is used for writing web pages. It has support for 
    media such as video and audio built in so does not need to rely on extras like Adobe Flash. Apple have chosen to use 
    HTML5 and not support Flash in iPhones and iTabs. Animations can also be developed directly in it although browser 
    support can be patchy at present.
  #cssinfo
    =link_to 'CSS3', 'http://en.wikipedia.org/wiki/CSS3#CSS3' , :class => 'floatbox'
    <br />CSS3 is the third revision of the Cascading Style Sheet language which is used to define the appearance of a web 
    page. As well as basic formatting CSS3 includes the ability to use multiple backgrounds, gradients, shadows, blurring 
    and simple animations (transitions). Again browser support is varied but improving….
  #jsinfo
    =link_to 'JavaScript', 'http://www.webopedia.com/TERM/J/JavaScript.html' , :class => 'floatbox'
    <br />A scripting language which allows developers to build interactive sites – ones which respond to user input, 
    mouse movements, clicks, finger swipes etc. It can even change the HTML code on the page to update parts of it 
    according to user choices – this is often used with Ajax.
  #jqinfo
    =link_to 'jQuery', 'http://www.webopedia.com/TERM/J/jQuery.html' , :class => 'floatbox'
    <br />jQuery is a JavaScript library giving developers easy access to the components of a web page and their events. 
    It simplifies the programming of complex animations and Ajax interactions.

  #ajinfo
    =link_to 'Ajax', 'http://www.webopedia.com/TERM/A/Ajax.html' , :class => 'floatbox'
    <br />Combined with JavaScript or jQuery Ajax allows just parts of the web page to be updated without reloading the 
    entire page. This is often combined with a request sent to the server to retrieve data from a database with the 
    response being updated on the web page.
  
  #mysqlinfo
    =link_to 'MySQL', 'http://www.webopedia.com/TERM/M/MySQL.html' , :class => 'floatbox'
    <br />MySQL is a free, open source relational database program used to store and query large amounts of data. 
    Typically used in web applications to securely store user and product details including shopping baskets, order 
    histories etc. 
  
  #rorinfo
    =link_to 'Ruby on Rails', 'http://www.webopedia.com/TERM/R/Ruby_on_Rails.html' , :class => 'floatbox'
    <br />Rails is an open source web application framework which uses all the above mentioned technologies to develop 
    robust, database driven web sites/applications. It also allows us to build a CMS (Content Management System) directly 
    into the site.  Massive sites such as Twitter, Yell.com, shopify, groupon, blurb… are built on Rails showing its power 
    and extensibility.
  
 

app/views/pages/the_founder.html.erb
<h1>Pages#the_founder</h1>
<p>Find me in app/views/pages/the_founder.html.erb</p>

app/views/pages/xhome.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p><%= home_path %></p>

app/views/webs/_alliancepublishingpress.html.haml
=image_tag 'webPortfolio/AlliancePublishingPresslrg.png', :title => 'www.alliancepublishingpress.com'

app/views/webs/_artificialdesigns.html.haml
=image_tag 'webPortfolio/ArtificialDesignslrg.png', :title => 'www.artificialdesigns.co.uk'

app/views/webs/bluedrummusic.html.erb
<h1>Webs#bluedrummusic</h1>
<p>Find me in app/views/webs/bluedrummusic.html.erb</p>

app/views/webs/elspics.html.erb
<h1>Webs#elspics</h1>
<p>Find me in app/views/webs/elspics.html.erb</p>

app/views/webs/lifestylepix.html.erb
<h1>Webs#lifestylepix</h1>
<p>Find me in app/views/webs/lifestylepix.html.erb</p>

app/views/webs/minnawaring.html.erb
<h1>Webs#minnawaring</h1>
<p>Find me in app/views/webs/minnawaring.html.erb</p>